### ISSUE TITLE
Offhand fireworks not working

### ISSUE THREAD

**Issue by Uzimattyan** [NemoNotFound/NemosFireworkKeybinding#1]
Expected behavior

When you have fireworks in your off-hand, pressing the “Firework” key during flight will use the fireworks.

Actual behavior

When you have fireworks in your off-hand, pressing the “Firework” key will throw items (e.g., ender pearls, splash potions) of Hotbar Slot 5 (regardless of whether you have it in your hand or not).

Minecraft 1.21
Firework Keybinding 1.1

By the way, I really like this mod!

Thanks for the development.

**Comment by NemoNotFound** [comment]
Oh, I thought I tested everything xD
thank you, I'll take a look soon! And I'm glad you like it :D

**Comment by NemoNotFound** [comment]
Are the fireworks being used? Actually the expected behaviour is that nothing happens while in off hand. Not sure anymore why I did that xD

That's also what I see in my testing

**Comment by NemoNotFound** [comment]
Ah never mind, something is broken xD

Will check it out!

**Comment by NemoNotFound** [comment]
Found the issue. Slots changed again in this version :D

**Comment by Uzimattyan** [comment]
Wow! What a quick response!

I checked the fix and it works correctly.

Thank you very much.

**Comment by NemoNotFound** [comment]
Amazing! I'll close the ticket then

**Comment by Uzimattyan** [comment]
Sorry to bother you again.

Please consider updating to past versions (especially 1.20.1) if you feel like it!

**Comment by NemoNotFound** [comment]
Sure, I'll take a look at :D
